RadeonOpenCompute/hcc

HC/WrapperGen/WrapperGen.cpp
tests/Unit/GridLaunch/accelerator_view.cpp

Tests:
ROCK: dev/5f38f1e4
ROCR: dev/0b9d0e1
```
Testing Time: 625.28s
Failing Tests (2):
CPPAMP :: Unit/HC/wg_size.cpp
CPPAMP :: Unit/HSAIL/shfl_xor.cpp
Expected Passes    : 657
Expected Failures  : 25
Unsupported Tests  : 10
Unexpected Failures: 2
```
HIP-privatestaging: privatestaging/31dc13d
HIP-Examples-privatestaging: privatestaging/23c7882
HIP all passed.

[GridLaunch] Fix an issue where passing a NULL accelerator_view would crash GridLaunch

---

CMakeLists.txt

up until now we use hcc build date as part of version string, in this commit
we change to use source commit date

[CMake] use source commit date as part of version string

---

include/hc_am.hpp
lib/hsa/hc_am.cpp
tests/Unit/Lock/lit.local.cfg
tests/Unit/Lock/lock_host_pointer.cpp
tests/Unit/Lock/unlock_host_pointer.cpp

Testing Time: 1061.88s
Failing Tests (12):
CPPAMP :: Unit/HC/memcpy_symbol1.cpp
CPPAMP :: Unit/HC/memcpy_symbol3.cpp
CPPAMP :: Unit/HC/wg_size.cpp
CPPAMP :: Unit/HSAIL/shfl_xor.cpp
CPPAMP :: Unit/ParallelSTL/is_partitioned_carray.cpp
CPPAMP :: Unit/Pool/accelerator_get_is_peer_api.cpp
CPPAMP :: Unit/Pool/map_to_peers_device_ptr.cpp
CPPAMP :: Unit/Pool/map_to_peers_host_ptr.cpp
CPPAMP :: Unit/SharedLibrary/shared_library1.cpp
CPPAMP :: Unit/SharedLibrary/shared_library2.cpp
CPPAMP :: Unit/SharedLibrary/shared_library3.cpp
CPPAMP :: Unit/SharedLibrary/shared_library4.cpp
Expected Passes    : 653
Expected Failures  : 25
Unsupported Tests  : 10
Unexpected Failures: 12

Memory lock api support for am memtracker

---

include/hc.hpp

This should go into the roc-1.0 branch too.

Add a generic implementation for hc::__builtin_bitextract_u32

---

HC/DirectFuncCall/DirectFuncCall.cpp
HC/WrapperGen/WrapperGen.cpp
tests/Unit/GridLaunch/customtype_byptr.cpp

Types in anonymous namespaces are labeled with "(anonymous namespace)" string. This PR resolves the parenthesis and space characters when generating the GridLaunch wrapper.
Clang will sometimes mark the kernel function with InternalLinkage if the arguments contain types in anonymous namespaces. This will interfere with the opt passes in clamp-link. This PR also resolves that issue by forcing GridLaunch kernel functions to the default ExternalLinkage.
Finally, this PR adds some additional debugging information when a type is unknown.
***
Tests:
ROCK: master/b0b2dee
ROCR: master/de0d9b5
```
Failing Tests (4):                        
CPPAMP :: Unit/HC/memcpy_symbol1.cpp  
CPPAMP :: Unit/HC/memcpy_symbol3.cpp  
CPPAMP :: Unit/HC/wg_size.cpp         
CPPAMP :: Unit/HSAIL/shfl_xor.cpp …
```

[GridLaunch] Fixes for anonymous namespace types

---

CMakeLists.txt
lib/clamp-hsatools.in

Instead of hardcoding the HSA_AMDGPU_GPU_TARGET at compile time,
autodetect it at runtime from the KFD topology.
Change-Id: I00af68084869ab4d439e70cf8816c1c8868f224d

[CMake] Autodetect HSA_AMDGPU_GPU_TARGET

---

include/hc.hpp
include/kalmar_runtime.h
lib/hsa/mcwamp_hsa.cpp

We define void* as the handle of i.e. queue, device, etc. And internally, it is a pointer to class member.
1. We will expose class member to outside, but good news is, we expose void*, and does not expose its  data type.
2. Make it hard to define getter method to const, because it also needs to declare the return value to be const too, then, cast from "a pointer to a constant member" to void*, which will also request const_cast.
In this change, only change what is easy, and for others, we may need to change the architect, which is not expected I believe.

Define const member function if needed

---

lib/clamp-hsatools.in

We need to wait until co-v2 support lands in LLVM before merging this.

clamp-hsatools: Use lld as the liner for AMDGPU

---

lib/hsa/mcwamp_hsa.cpp
tests/Unit/AmpMath/amp_math_erf_precise_math.cpp
tests/Unit/AmpMath/amp_math_erfc_precise_math.cpp

This pull request consists fixes in runtime and unit tests for LC backend.
Failing HCC unit tests with HSAIL backend
======================================
CPPAMP :: Unit/HSAIL/shfl_xor.cpp
@scchan is working on getting this fixed
Failing HCC unit tests with LC backend
======================================
Binaries for these 2 tests would run indefinitely. They pass if compiled with HSAIL backend.
Temporary let them fail immediately if compiled with LC backend.
Incorrect result with LC backend. It passes with HSAIL backend.
CPPAMP :: Unit/DynamicTileStatic/test12.cpp
CPPAMP :: …

Fixes to unit tests for LC backend

---

include/hc.hpp
include/hc_defines.h
tests/Unit/HSAIL/activelaneid.cpp
tests/Unit/HSAIL/activelanepermute.cpp
tests/Unit/HSAIL/shfl.cpp
tests/Unit/HSAIL/shfl_down.cpp
tests/Unit/HSAIL/shfl_up.cpp
tests/Unit/HSAIL/shfl_xor.cpp

- added __lane_id() and changed a few unit tests to use lane_id
- added __wavesize() for LC
- fixed shfl_xor on hsail
Testing Time: 193.42s
Failing Tests (24):
CPPAMP :: Unit/AmpShortVectors/hc_short_vector_device.cpp
CPPAMP :: Unit/DynamicTileStatic/test12.cpp
CPPAMP :: Unit/DynamicTileStatic/test13.cpp
CPPAMP :: Unit/DynamicTileStatic/test6.cpp
CPPAMP :: Unit/GridLaunch/linkobj.cpp
CPPAMP :: Unit/HC/get_group_segment_sizes.cpp
CPPAMP :: Unit/HC/memcpy_symbol1.cpp
CPPAMP :: Unit/HC/memcpy_symbol2.cpp
CPPAMP :: Unit/HC/memcpy_symbol3.cpp
CPPAMP …

various fixes for shfl unit tests, added  __wavesize for lc

---

lib/hsail-amdgpu-wrapper.ll

As used in the hsail_get_lane_id() intrinsic, these intrinsics
always return a value between 0 and 63.  The range metadata
gives this information compiler to help improve the optimizer.

hsail-amdgpu-wrapper: Add range metadata to mbcnt intrinsics

---

lib/mcwamp.cpp

- rocr team requests hcc not to load the libhsa-runtime64 library from its soname
- platform detection could be achieved by loading the hcc runtime library since it depends on either libhsa-runtime or libOpenCL

avoid loading compute platform library during platform detection

---

lib/hsail-amdgpu-wrapper.ll

This reverts commit 0213640450ee5af2a50643e5bf6e93c74c3bdd18.
This is entirely incorrect. v_mad_f32 is not equivalent to fma.
We also very much do not want to be using inline asm for common
operations.

Revert "[builtin][LC] use inline assembly for 32-bit FMA operation"

---

amp-conformance/output-to-junit.pl
amp-conformance/run_tests.pl.in

If a test list is passed in, and the test is not present, the system
will try to execute that test and return "Invalid or cannot open" .
This will cause the test_results.xml file to truncate at the invalid
test. Handle a non-existent test and ensure that the test is present
before adding it to the list of tests.
Change-Id: Ib9b368aa29f1c8de25b62760d771b05f8054a9a9

Fix handling of invalid/missing tests

---

lib/hsail-amdgpu-wrapper.ll

this builtin is sensitive to the # of active workitems, mark it as convergent to prevent optimization from moving it around...

mark activelanemask in wrapper as convergent

---

tests/Unit/HSAIL/ballot.cpp

Adding one additional unit test for the ballot builtin.  This test would fail currently due to a bug in the backend.  A fix has been implemented and is waiting to be upstreamed.

add one additional ballot unit test

---

tests/Unit/GridLaunch/customtype_byval.cpp
tests/Unit/GridLaunch/hc_attr_in_struct.cpp

This pull request tests the corresponding commit from hcc-clang repo.
The test case is adapted from [Issue #24](https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/issues/24).
make test:
```
Testing Time: 264.60s
Expected Passes    : 676
Expected Failures  : 25
Unsupported Tests  : 10
[100%] Built target test
```
***
HIP-privatestaging/privatestaging/4d8e2d79 test cases:
```
37/37 Test #37: hipDynamicShared.tst ...................***Exception: Other  0.10 sec
97% tests passed, 1 tests failed out of 37
Total Test time (real) =  33.81 sec
The following tests FAILED:
37 - hipDynamicShared.tst (OTHER_FAULT)
```
***
HIP-Examples-privatestaging/privatestaging/481050f4
Most tests pass with the following exceptions:
The following were skipped because they appear to break ssh sessions and in …

Add test cases for calling a member function with hc attribute inside a GridLaunch kernel

---

lib/opencl/mcwamp_opencl.cpp

For some CL implementations clGetDeviceIDs does not set num_devices
(to 0) when no device is found.

Fix possibly undefined behavior on OpenCL Device not found.

---

lib/hsa/mcwamp_hsa.cpp

This fixes a problem where the `dependentAsyncOpVector` in the `bufferKernelMap` is never cleared, instead just a local copy is cleared. This drastically improves performances when the program launches a lot of kernels.

Fix performance problem when launching lots of kernels

---

lib/mcwamp_main.cpp

Please note, that I have omitted --verbose & --brief since they appear to have no function.
The descriptions are based on the source code; I hope they are ok like this.
Also C++11 is needed, since raw string literals are used (I can change this, if needed).

implement --help for hcc-config / clamp-config

---

lib/hsa/mcwamp_hsa.cpp

With this change, errors and bad dmesg errors generated by HIP samples which launch more than 32k kernels is fixed.

added fix for signal overflow for kernels

---

lib/CMakeLists.txt
scripts/cmake/MCWAMP.cmake

This removes the dependency on hcc runtime

compile hcc-config and clamp-config in non-amp mode

---

lib/hc-kernel-assemble.in

the driver would replace the IR from clang with the one set from env var HC_REPLACE_GPU_FE_LLVM on the gpu path

Env Var to replace LLVM IR from clang on GPU path

---

CMakeLists.txt

The computation for KALMAR_VERSION_PATCH was incorrectly using +%y%W%w for formatting the date whereas it should be +%y%U%w.

Fixed KALMAR_VERSION_PATCH computation

---

lib/doxygen_config.in

this is needed for doxygen to generate docs for builtins that are only available to amdgpu backend

define __hcc_backend__ to HCC_BACKEND_AMDGPU in doxygen

---

lib/hsa/mcwamp_hsa.cpp
tests/Unit/HC/multi_acc.cpp
tests/Unit/HC/multi_acc_array.cpp

replace hsa_memory_copy with memory pool async copy.
no regression found:
HCC_RUNTIME=HSA make test
Testing Time: 128.52s
Failing Tests (18):
CPPAMP :: Unit/HC/memcpy_symbol1.cpp
CPPAMP :: Unit/HC/memcpy_symbol2.cpp
CPPAMP :: Unit/HC/memcpy_symbol3.cpp
CPPAMP :: Unit/HC/memcpy_symbol4.cpp
CPPAMP :: Unit/HSAIL/activelaneid.cpp
CPPAMP :: Unit/HSAIL/activelanepermute.cpp
CPPAMP :: Unit/ParallelSTL/is_partitioned_carray.cpp
CPPAMP :: Unit/ParallelSTL/sort_carray.cpp
CPPAMP :: Unit/ParallelSTL/sort_stdarray.cpp
CPPAMP :: …

Replace hsa_memory_copy

---

CMakeLists.txt
tests/CMakeLists.txt

This sets up the cmake to call the 'ProcessorCount' module to build and test with all the cores available, instead of just setting it to 8.

Utilize all the cores when building and running tests

---

amp-conformance/Tests/2_Cxx_Lang_Exte/2_3_Expr_Invo_Rest_Func/2_3_2_Func_Over/Special_member_functions/defaulted_copy_assign_op.01/test.cpp
amp-conformance/Tests/2_Cxx_Lang_Exte/2_3_Expr_Invo_Rest_Func/2_3_2_Func_Over/Special_member_functions/defaulted_copy_ctor.01/test.cpp

[Problem]
Clang 4.0 reports an error "default initialization of an object of const type 'const XXX' without a user-provided default constructor" on some of const declarations without explicit initialization. 
[Explanation]
All the problematic declarations are of the objects inherited from POD classes, which are not initialized by default. 
C++ spec says: "If a program calls for the default-initialization of an object of a const-qualified type T, T shall be a class type with user-provided default constructor" ... 7.1.7.1 The cv-qualifiers ... "the definition of an object or subobject of const-qualified type must specify an initializer or be subject to default initialization."
[Conclusion]
The error reported by Clang 4.0 is valid and conforms to C++ spec, because the reported const …

[LIGHTNING-306] Fix amp-conformance tests, on which Clang 4.0 reasonably reports error for ill-formed const object declaration.

---

HC/WrapperGen/WrapperGen.cpp
include/hc.hpp
lib/hc-kernel-assemble.in
tests/Unit/HC/get_use_count.cpp
tests/benchEmptyKernel/Makefile
tests/benchEmptyKernel/bench.cpp

Optimize dispatch latency, cleanup benchmark, add completion_future::get_use_count.
--
Testing Time: 309.57s
Failing Tests (23):
CPPAMP :: Unit/HC/amdgcn_ds_swizzle_bitmode.cpp
CPPAMP :: Unit/HC/amdgcn_ds_swizzle_qdmode.cpp
CPPAMP :: Unit/HC/create_blocking_marker.cpp
CPPAMP :: Unit/HC/create_blocking_marker2.cpp
CPPAMP :: Unit/HC/memcpy_symbol1.cpp
CPPAMP :: Unit/HC/memcpy_symbol2.cpp
CPPAMP :: Unit/HC/memcpy_symbol3.cpp
CPPAMP :: Unit/HC/memcpy_symbol4.cpp
CPPAMP :: Unit/HSAIL/activelaneid.cpp
CPPAMP :: Unit/HSAIL/activelanepermute.cpp
CPPAMP …

Bench latency fix2

---

include/hc.hpp

Add C implementations for a few functions since we  no longer have a wrapper library that implements them.

Clang tot builtin fixes

---

.gitmodules

The current urls don't seem to work if I don't have an ssh key.
I don't have any experience using submodules, but this seems to work for me.

submodule: Update the submodule config to allow anonymous checkouts

---

include/kalmar_runtime.h

The issue is that KalmarQueue::copy() doesn't work on a multi-gpu system since the hsa version is implemented with hsa_memory_copy.  The fallback on read() or write() fixes that and the test hcc/tests/Unit/HC/multi_acc_array.cpp, which contains array copies of cpu->device and device ->cpu in a multi-gpu env, is passing now
No new regressions:
HCC_RUNTIME=HSA make test
Testing Time: 543.92s
Failing Tests (14):
CPPAMP :: Unit/AmpMath/amp_math_log.cpp
CPPAMP :: Unit/HC/create_blocking_marker.cpp
CPPAMP :: Unit/HC/create_blocking_marker2.cpp
CPPAMP …

fix array copy on multi-gpu system

---

lib/hsa/unpinned_copy_engine.cpp

Changed memory pool for staging buffers from COARSE grain to FINE grain for supporting HIP on APUs.

Fix for running HIP on APUs
